# PARAMETERS TO CONTROL THE BEHAVIOR OF THE GAME ENGINE
# DO NOT REMOVE OR RENAME THIS FILE
PLAYER_1_NAME = 'logs/A'
PLAYER_1_PATH = './player'
PLAYER_1_SERVER_MESSAGES_PATH = 'logs/A.messages.server'
PLAYER_1_PLAYER_MESSAGES_PATH = 'logs/A.messages.player'
# NO TRAILING SLASHES ARE ALLOWED IN PATHS
PLAYER_2_NAME = 'logs/B'
PLAYER_2_PATH = './player'
PLAYER_2_SERVER_MESSAGES_PATH = 'logs/B.messages.server'
PLAYER_2_PLAYER_MESSAGES_PATH = 'logs/B.messages.player'
# GAME PROGRESS IS RECORDED HERE
GAME_LOG_FILENAME = 'logs/gamelog'
# PLAYER_LOG_SIZE_LIMIT IS IN BYTES
PLAYER_LOG_SIZE_LIMIT = 524288
# STARTING_GAME_CLOCK AND TIMEOUTS ARE IN SECONDS
ENFORCE_GAME_CLOCK = True
STARTING_GAME_CLOCK = 30.
BUILD_TIMEOUT = 10.
CONNECT_TIMEOUT = 10.
# THE GAME VARIANT FIXES THE PARAMETERS BELOW
# CHANGE ONLY FOR TRAINING OR EXPERIMENTATION
NUM_ROUNDS = 1000
STARTING_STACK = 2
ANTE = 1
BET_SIZE = 1
