# PARAMETERS TO CONTROL THE DEFAULT BEHAVIOR OF THE GAME ENGINE
PLAYER_1_NAME = 'A'
PLAYER_1_PATH = './players/default'
# NO TRAILING SLASHES ARE ALLOWED IN PATHS
PLAYER_2_NAME = 'B'
PLAYER_2_PATH = './players/default'
# GAME PROGRESS IS RECORDED HERE
GAME_LOG_FILENAME = 'gamelog'
SCORE_FILENAME = 'scores'
LOGS_PATH = 'logs'
# PLAYER_LOG_SIZE_LIMIT IS IN BYTES
PLAYER_LOG_SIZE_LIMIT = 524288
# STARTING_GAME_CLOCK AND TIMEOUTS ARE IN SECONDS
ENFORCE_GAME_CLOCK = True
STARTING_GAME_CLOCK = 30.
BUILD_TIMEOUT = 10.
CONNECT_TIMEOUT = 10.
